BERT_MODEL_NAME: google/muril-base-cased
batch_size: 8
cache_dir: ./cache_dir
data_dir: ./data/kfold
early_max_stopping: 8
epochs: 50
hidden_dim: 256
kfolds: 5
learning_rate: 0.001
model: bert_lstm
model_name: model_checkpoint_non_concat_muril_lstm_lr_0_001
model_save_dir: ./saved_model_dir
n_layers: 1
output_dim: 2
train_type: non_concat
unfreeze: false
visualize: false
weight_decay: 0.001
